# Generated by Django 4.2.2 on 2024-03-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, verbose_name='uid')),
                ('nickname', models.CharField(max_length=100, verbose_name='昵称')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('date', models.DateField(verbose_name='日期')),
                ('polarity', models.CharField(max_length=10, verbose_name='评论情感极性')),
                ('probability', models.FloatField(verbose_name='评论情感概率')),
            ],
        ),
    ]
